### PR TITLE
Closes #66

### LINKED ISSUE #66: Add Roles table to mySQL database
Links to #65 

Add a Roles table with user email and role

### PR DESCRIPTION
**Pull request by humzzahargan**

### CODE REVIEW

**Review by TheodoreRamey — CHANGES_REQUESTED** [review]
Role shouldn’t be UNIQUE as far as I understand, many users may have the same role. Also, can you change the users table to also not have UNIQUE for first and last name, users may share first or last names.

**Comment by jacksontheel** [comment]
I think what we ought to be doing here is a table for roles where the only property is a id and a VARCHAR for the role itself. Then, in the user table, we have a foreign key property to one of the roles.

**Comment by humzzahargan** [comment]
Made it so the roles management table has the role and level of permission the role has. Let me know what yall think

**Review by jacksontheel — APPROVED** [review]
Love it

**Review by TheodoreRamey — APPROVED** [review]

**Review by c-lawrence — APPROVED** [review]
Looks good!

**Pull request merged**
