### PR TITLE
Admin page front-end work

### PR DESCRIPTION
**Pull request by jacksontheel**
No buttons on jackson@gmail.com because that's the user I'm logged in as. The "Admin" link in the sidebar is only visible if you're an admin.

image

### CODE REVIEW

**Comment by Phillipnewell** [comment]
I tested this a bunch and I want to note that we'd have to be careful how we append /f22-gneiss because that can get pretty hairy. The admin-promoting and demoting works like a charm.

**Comment by Phillipnewell** [comment]
f22-bug

**Comment by Phillipnewell** [comment]
Idk if this was happening before, I ran an "npm ci" and it was still there. I have a talent for breaking things, I swear.

**Comment by Phillipnewell** [comment]
This extra /f22-gneiss occurs on dummy packets so this might be a non-issue...

**Review by Phillipnewell — APPROVED** [review]
The Admin section disappears reliably.

**Comment by jacksontheel** [comment]
> f22-bug

This has been fixed in the latest commit. Thanks!

**Pull request merged**
